// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUMkiNgxAqRT5ZD0HhoDsDMz3I1Cepu4',
    appId: '1:259496958210:web:85f0e8735521c17b780a1b',
    messagingSenderId: '259496958210',
    projectId: 'smartcrop-efd5e',
    authDomain: 'smartcrop-efd5e.firebaseapp.com',
    databaseURL: 'https://smartcrop-efd5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartcrop-efd5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWKfG86jzPihHygY0-fnaLhTal7_9Fc0M',
    appId: '1:259496958210:android:1112bf9cca2e43bf780a1b',
    messagingSenderId: '259496958210',
    projectId: 'smartcrop-efd5e',
    databaseURL: 'https://smartcrop-efd5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartcrop-efd5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgknFtz0JUnVcFEjT2kcxkGc2aBPbtlks',
    appId: '1:259496958210:ios:ff1b7fe5bd06bacb780a1b',
    messagingSenderId: '259496958210',
    projectId: 'smartcrop-efd5e',
    databaseURL: 'https://smartcrop-efd5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartcrop-efd5e.firebasestorage.app',
    iosClientId: '259496958210-fbpvjh9pomebpqlgfkk6v36dvtjunol9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgknFtz0JUnVcFEjT2kcxkGc2aBPbtlks',
    appId: '1:259496958210:ios:ff1b7fe5bd06bacb780a1b',
    messagingSenderId: '259496958210',
    projectId: 'smartcrop-efd5e',
    databaseURL: 'https://smartcrop-efd5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartcrop-efd5e.firebasestorage.app',
    iosClientId: '259496958210-fbpvjh9pomebpqlgfkk6v36dvtjunol9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxUMkiNgxAqRT5ZD0HhoDsDMz3I1Cepu4',
    appId: '1:259496958210:web:61c869468d11a4c3780a1b',
    messagingSenderId: '259496958210',
    projectId: 'smartcrop-efd5e',
    authDomain: 'smartcrop-efd5e.firebaseapp.com',
    databaseURL: 'https://smartcrop-efd5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartcrop-efd5e.firebasestorage.app',
  );
}
